import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';

const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const labels = { survived: 'Survived', 'failed-during-disruption': 'Failed, then recovered', 'recovery-failed': 'Recovery failed', 'invalid-baseline': 'Invalid baseline', unverified: 'Fault not observed', 'not-exercised': 'No fault observed in check window' };
const cell = result => `<td><span class="${result.pass ? 'pass' : 'fail'}">${result.pass ? 'PASS' : 'FAIL'}</span><small>${result.durationMs} ms · ${result.status === null ? 'no response' : 'HTTP ' + result.status}</small>${result.reasons.map(r => `<small>${escape(r)}</small>`).join('')}</td>`;

export function renderReport(report) {
  const eligible = report.workflows.filter(w => w.baseline.pass && w.disruption.proxy.injected > 0).length;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pull the Plug — ${escape(report.name)}</title><style>
  :root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#192536;background:#f4f6f9}*{box-sizing:border-box}body{margin:0}main{max-width:1120px;margin:auto;padding:56px 28px}.brand{font-size:13px;letter-spacing:.16em;font-weight:800;color:#52627b}h1{font-size:clamp(32px,5vw,56px);letter-spacing:-.05em;margin:28px 0 12px;line-height:1.05}p{color:#52627b;line-height:1.6}.headline{font-size:23px;color:#192536;max-width:760px}.stats{display:flex;gap:18px;flex-wrap:wrap;margin:32px 0}.stat{background:white;border:1px solid #dfe5ed;border-radius:12px;padding:22px;min-width:180px}.stat strong{display:block;font-size:38px}.stat span{color:#52627b;font-size:14px}.badge{display:inline-block;padding:7px 12px;border-radius:30px;background:${report.verified ? '#e4f4ed' : '#fff0d5'};color:${report.verified ? '#176044' : '#79520c'};font-size:13px;font-weight:650}.table-wrap{overflow-x:auto;border:1px solid #dfe5ed;border-radius:12px;background:#fff}table{width:100%;border-collapse:collapse;text-align:left}th{font-size:12px;text-transform:uppercase;letter-spacing:.07em;color:#52627b;background:#f9fafc}th,td{padding:19px 18px;border-bottom:1px solid #e8edf3}tr:last-child td{border-bottom:0}small{display:block;font-size:12px;color:#65758a;margin-top:7px}.pass{color:#176044;font-weight:750}.fail{color:#a53636;font-weight:750}.note{padding:20px 0;font-size:14px}footer{margin-top:32px;font-size:12px;color:#65758a;border-top:1px solid #dfe5ed;padding-top:22px}code{font-family:ui-monospace,monospace} @media(max-width:600px){main{padding:32px 16px}.stat{min-width:140px;flex:1}th,td{padding:14px 10px}}
  </style></head><body><main><div class="brand">PULL THE PLUG / EXPERIMENT REPORT</div><h1>${escape(report.name)}</h1><p class="headline">${report.verified ? `${report.summary.survived} of ${eligible} baseline-valid workflows with a fault observed in their check window passed during disruption and after restoration.` : 'The app did not encounter an injected fault. This run cannot establish resilience.'}</p><span class="badge">${report.verified ? 'Fault observed at the proxy' : 'Unverified experiment'} · ${escape(report.fault.type)}</span><div class="stats"><div class="stat"><strong>${report.summary.survived}</strong><span>Survived</span></div><div class="stat"><strong>${report.summary['failed-during-disruption']}</strong><span>Failed, then recovered</span></div><div class="stat"><strong>${report.summary['recovery-failed']}</strong><span>Recovery failed</span></div></div><div class="table-wrap"><table><thead><tr><th>Workflow</th><th>Baseline</th><th>Disruption</th><th>Recovery</th><th>Outcome</th></tr></thead><tbody>${report.workflows.map(w => `<tr><td><strong>${escape(w.name)}</strong><small>${w.disruption.proxy.injected} injected requests in disruption check window</small></td>${cell(w.baseline)}${cell(w.disruption)}${cell(w.recovery)}<td>${labels[w.outcome]}</td></tr>`).join('')}</tbody></table></div><p class="note">Scope: only requests routed through the configured proxy are disrupted. Counters are measured during each sequential check; background traffic can affect attribution. Checks run once per phase. Passing means the supplied assertions passed, not that the entire application is resilient. A check with no observed fault is excluded from the survival count.</p><footer>Generated ${escape(report.createdAt)} · Injected requests: ${report.phases[1].proxy.injected} · No request bodies, credentials, or response bodies are stored in this report.</footer></main></body></html>`;
}

export async function saveReport(report, directory) {
  const dir = resolve(directory);
  await mkdir(dir, { recursive: true });
  const json = join(dir, 'report.json');
  const html = join(dir, 'report.html');
  await writeFile(json, JSON.stringify(report, null, 2) + '\n');
  await writeFile(html, renderReport(report));
  return { json, html };
}
